### ISSUE TITLE
Port to python 3

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1000]
Given the discussion in Factory about switching to python 3 as default it likely is worth investigating any python 3 related issues and if nothing else enabling testing on python 3.

**Comment by mimi1vx** [comment]
@jberry-suse one big issue - osc itself

**Comment by jberry-suse** [comment]
hmm, there was a presentation or something about osc2 recently perhaps I should investigate that.

**Comment by plusky** [comment]
osc2 is afaik only python2 as well

**Comment by jberry-suse** [comment]
hehe, ok...so we get to be "one of those projects" mentioned in the mailing list. :)

Well short of dropping osc dependency it looks like we have to wait for them. Perhaps we should poke them about it?
