### ISSUE TITLE
devel-project.py: extend to include check for factory-maintainer group on devel projects

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1001]
Per discussion in IRC starting from #983 it seems to make sense to add a check that the `factory-maintainer` group is included as a maintainer of all devel projects as it will be needed when a package is removed due to no longer being maintained.

**Comment by lnussel** [comment]
yes. And I still have on my todo to open a task to extend that to factory-staging

**Comment by DimStar77** [comment]
*factory-maintainers* (plural) is the group - factory-maintainer (singular) is a person (coolo)

**Comment by jberry-suse** [comment]
Yeah, typo. Thanks for noting that.

**Comment by jberry-suse** [comment]
I posed in PR, but I'll mirror here. Any interest into auto requesting for projects missing the group(s)?

```
osc requestmaintainership PROJECT group:NAME
```
