### ISSUE TITLE
repo_checker: resolve installcheck/fileconflict issues in Factory rings

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1012]
[Relevant issues](https://gist.githubusercontent.com/jberry-suse/99329e902ecae6a03a903fa8623c0ce3/raw/23bbb36d1b3f37dd1ea50cee49d958f00d36bfe9/repo_checker.openSUSE:Factory:Staging:L)

Meta issue to track bugs and submit requests.

**Comment by jberry-suse** [comment]
[llvm4](https://build.opensuse.org/request/show/508876) and [llvm3_8](https://build.opensuse.org/request/show/508877)

**Comment by jberry-suse** [comment]
[dummy-release](https://build.opensuse.org/request/show/511064) conflict with `openSUSE-Kubic-release`

**Comment by jberry-suse** [comment]
[installation-images](https://build.opensuse.org/request/show/511067) all subpackages

**Comment by jberry-suse** [comment]
Looks like primarily:
```
found conflict of libopenssl-1_0_0-devel-32bit-1.0.2l-2.2.x86_64 with libopenssl-1_1_0-devel-32bit-1.1.0f-1.3.x86_64:
  - /usr/lib/libcrypto.so
  - /usr/lib/libssl.so
```
and
```
found conflict of openSUSE-Kubic-release-20170704-2.1.x86_64 with openSUSE-release-20170704-3.1.x86_64:
  - /etc/motd
  - /etc/os-release
```

installation-images resolves most of them.

@DimStar77 What's the best way to solve the `*-release` ones? I already fix dummy-release, but they should all probably just provide a "release" virtual package and conflict with other providers. Do you have a preference?

**Comment by jberry-suse** [comment]
[openssl-1_1_0](https://build.opensuse.org/request/show/511068) conflict with [openssl-1_0_0](https://build.opensuse.org/request/show/511069)

**Comment by jberry-suse** [comment]
@DimStar77 Also given that openssl-1_1_0 fails to build for i586 in Factory and devel I suppose this update will not translate to a fix since no new rpms will be produced. Given the number of problems indicated perhaps a special fix will be needed (binary wipe of -devel or ugly temporary whitelist for repo checker).

**Comment by DimStar77** [comment]
> @DimStar77 What's the best way to solve the *-release ones? I already fix dummy-release, but they should all probably just provide a "release" virtual package and conflict with other providers. Do you have a preference?

They all provide /distribution-release' - adding a conflict sounds like a good idea

**Comment by DimStar77** [comment]
> openssl-1_1_0 conflict with openssl-1_0_0

in the -32bit packages; those have not been caught by the old fileconflict checker, and thus are not surprising. I'll file a bug for the product, so the maintainer can fix it

**Comment by DimStar77** [comment]
> openssl-1_1_0 conflict with openssl-1_0_0

Old repo-checker did not inspect the -32bit packages, so there will probably be many more of such cases; thanks for the fix

**Comment by jberry-suse** [comment]
Thanks @DimStar77 for adding the conflict to `_product` packages. I updated my [dummy-release](https://build.opensuse.org/request/show/511312) SR to follow the same format. Once all of these land I'll run the repo checker again and hopefully all will be ready for switching.

**Comment by jberry-suse** [comment]
installation-images SR has stalled without a clear reason, but all others have been accepted.

**Comment by jberry-suse** [comment]
I am considering adding a package whitelist so that we can deploy this and prevent additional issues from creeping in as this is delaying things quite a bit. The whitelisted packages can be removed as the issues are resolved.

**Comment by jberry-suse** [comment]
Since #1033 was indeed hiding more issues :( :( I will go ahead and add a whitelist feature and file bug reports for the rest. Likely the whitelist can be used for Leap 15 and SLE 15 to ease them onto the checker as well.

**Comment by jberry-suse** [comment]
No longer blocking deployment in favor of whitelist. Will leave open to track the clearing of the whitelist.

**Comment by jberry-suse** [comment]
This appears to be a longer term goal since a lot of folks are not terribly responsive. The mechanisms are in place to do this in a controlled manor without causing interuption so I'll close this in favor of staging masters taking a look at whitelists once in a while.
