### ISSUE TITLE
repo_checker: workflow for Leap 15 / SLE 15

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1015]
Presumably we are looking to have the new `repo_checker` for 15 and not far behind SLE 15. I imagine it makes sense to resolve any issues in Leap 15 first and forward such changes to SLE 15.

The question of the workflow comes to mind. For Factory `check_source.py` is responsible for adding `factory-repo-checker` user to requests after they pass its checks. For Leap 15 we could do a few different approaches:

- add as required review to project added to all requests (presumably requests are declined by other bots anyway)
- run `check_source` bot on Leap; could either run through `leaper` or by itself. could also skip actual review bits for requests not coming from already checked sources like `SLE-workarounds`, but still add `repo-checker`
- modify `leaper` to add the review in the same manor as `check_source` (ie once it passes its checks [or at least not initially declined])

Given the new `repo_checker` will wait for requests to be staged and build successfully adding the review to project may be simplest as it is a required review just as legal review, but obviously other reviews may decline before `repo_checker` runs.

The one caveat being that `check_source` will skip the entire staging process for requests that only include modifications to `.changes` files. I would imagine that many times those requests are then forwarded on to Leap and should likely have the same skip applied. As such it seems to make sense to perhaps run `check_source` after reviewing it for any needed Leap related modifications. I would imagine `leaper` could remain a total separate review as it is more concerned with the Leap workflow the request contents.

With all that in mind, the second choice, running `check_source` with some tweaks for Leap, seems like a good path forward. Thoughts?

**Comment by lnussel** [comment]
or use Leaper as generic gate keeper and just skip the origin logic for Factory?

**Comment by lnussel** [comment]
in any case for packages that are forked in Leap we should apply the exact same checks as for Factory

**Comment by jberry-suse** [comment]
Do we want to go ahead and deploy this for Leap 15.0 and SLE 15?
