### ISSUE TITLE
repo_checker: rename sub-packages of existing package can cause false file conflicts

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1044]
See https://build.opensuse.org/request/show/510161 for an example where both checkers see:

```
found conflict of python3-zope-proxy-4.1.1-6.2.x86_64 with python3-zope.proxy-4.2.1-10.2.x86_64
```

Note the rename from `-proxy` to `.proxy`. This should be a matter of using the binaryversions query to determine the binaries produced in target project for all packages within a staging project rather than looking at the binaries produced in the staging and ignoring the versions from the target project.

Both repo checkers use the same workflow style here, only the old one one would get the list from the devel project using lots of API calls whereas the new one uses the binary list produced by `bs_mirrorfull` from the staging project.

Since this is a pre-existing bug I would not expect this to prevent deployment. I am curious however why I have not seen reports about this before as clearly this request has been pending the old repo checker review for over 20 days (ie stuck on this). I can't imagine this is the first case where something like this is manually skipped. Would be good to know of any other cases Factory maintainers are familiar with.

**Comment by DimStar77** [comment]
actually, a package rename should obsolete the old package name - such is the packaging guideline convention... so I would argue that this conflict is not even wrong at all

**Comment by jberry-suse** [comment]
Although, I imagine the error message does not communicate that desire clearly. Not sure how we want to handle this going forward. The current bot is running with my WIP branch that ignores the previous set of binaries provided by the same packages. The algorithm is as follows.

- binary list from staging project
- package list that provides those binaries
- binaries list those packages provide in target project

Some sudo code, if that makes it more clear:
```
binaries('openSUSE:Factory', packages(binaries('Staging:A')))
```

This handles the `ghc-*` case of inherited packages only partially enabled, along with renames, and letter stagings, and delete requests.

The process is then:

- write all package information for target project binaries while ignoring those in list generated by previous algorithm
- write all package information for staging project (which should contain the ignored packages)

Including all binaries from the target project will result in those self conflicts that we saw during the less hot hotfix.

Could do some package-by-package binary diffing to find renames and include those in install check or perhaps only file conflicts in an isolated check just between new and old binaries. If anything is returned parse the packages and provide a rename warning as obsoletes or similar should avoid a conflict.
