### ISSUE TITLE
000product needs special handling for sle15

### ISSUE THREAD

**Issue by coolo** [openSUSE/osc-plugin-factory#1049]
There are various issues with handling 000product:

- images should build on local - (possibly also on OBS meanwhile, but for sure on IBS), freeze reverts that unfortunately
- 000product needs to be build disabled when selected, it has too many unrelated products
- 000product.local needs to have its service triggered whenever 000product changes (e.g. also on freeze cmd)

All these 3 things need to be remembered at the moment to be done manually

**Comment by coolo** [comment]
small correction: images repo needs to be build disabled completely - and only 000product.local needs to be enabled. disabling 000product is not possibly unless it's actually selected otherwise

**Comment by coolo** [comment]
And in case this needs reproducing, it's important to branch from staging to staging:
- iosc rdelete -mgo SUSE:SLE-15:GA:Staging:A 000product.local
- iosc branch SUSE:SLE-15:GA:Staging:A 000product SUSE:SLE-15:GA:Staging:A 000product.local
- build enable 000product.local

**Comment by coolo** [comment]
One more: you also need to enable publishing for 000product.local (only if you recreate it of course)

**Comment by coolo** [comment]
The basic change - without any options

```
diff --git a/osclib/freeze_command.py b/osclib/freeze_command.py
index 880bae9..4a3b2f1 100644
--- a/osclib/freeze_command.py
+++ b/osclib/freeze_command.py
@@ -182,6 +182,7 @@ class FreezeCommand(object):
         f = ET.SubElement(root, 'build')
         # this one stays
         ET.SubElement(f, 'disable', {'repository': 'bootstrap_copy'})
+        ET.SubElement(f, 'disable', {'repository': 'images'})
         # this one is the global toggle
         ET.SubElement(f, 'disable')
         f = ET.SubElement(root, 'publish')
@@ -204,6 +205,8 @@ class FreezeCommand(object):
         r = ET.SubElement(root, 'repository', {'name': 'images', 'linkedbuild': 'all', 'rebuild': 'direct'})
         ET.SubElement(r, 'path', {'project': prj, 'repository': 'standard'})
         a = ET.SubElement(r, 'arch')
+        a.text = 'local'
+        a = ET.SubElement(r, 'arch')
         a.text = 'x86_64'
 
         if 'ppc64le' in self.api.cstaging_archs:
```

**Comment by coolo** [comment]
Grr, osc branch ignores the arguments and links to the ring1 - so you need to use linkpac+linktobranch

**Comment by coolo** [comment]
wow, one more thing to add for recreating 000product.local:
iosc cat SUSE:SLE-15:GA:Rings:1-MinimalX 000product _multibuild > _multibuild
iosc add _multibuild
iosc ci -madd

**Comment by coolo** [comment]
followed by iosc service rr - this is crazy :(

**Comment by coolo** [comment]
ok, service and branches just don't work together - so we need a more basic approach

**Comment by lnussel** [comment]
fixed meanwhile
