### ISSUE TITLE
repo_checker: process stagings that failed due only to openqa

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1069]
repochecker now uses the overall state that the staging plugin reports before reviewing:
https://github.com/openSUSE/osc-plugin-factory/blob/master/repo_checker.py#L114

Currently looking at M and apparmor the staging has actually finished building but fails in openQA. So the overall state is failed and repochecker doesn't check the package. I'd suggest to look at the build result only to speed things up.

**Comment by jberry-suse** [comment]
I debated this when I wrote it. Ended up decided to keep it simple since failed may also indicate build failures and will be blocked by openqa (a much more expensive check). It is likely worth doing just to provide earlier feedback.
