### ISSUE TITLE
Docker image need a update otherwise travis fails to finish

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#1071]
travis fails to finish in the recent pull request, like https://travis-ci.org/openSUSE/osc-plugin-factory/jobs/265920481 , it seems docker image need a update.

**Comment by jberry-suse** [comment]
I updated it (done automatically every Saturday), I'll also add a `zypper dup` to the script before the `zypper in` as that would solve the issue.
