### ISSUE TITLE
repo-checker no longer blocks invalid licenses

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#1102]
The old repo-checker inspected rpmlint.log and did not let packages pass with an invalid license.

The main issue here is that rpmlint-Factory-strict is not enabled across OBS - as it is too annoying in devel projects and even worse in 3rd party repos... so the invalid licenses are flagged as warnings there only

In adi stagings, this is also not enabled (as it builds against openSUSE:Factory/standard - just like any other 3rd party prj would) - 'proper' staigngs are fine, as they build against openSUSE:Factory:Staging/standard, where the strict filter is injected unconditionally

We need to either find a setup that works for adi to get Factory-strict enabled or have repo-checker kick this out again, as in the past.

**Comment by jberry-suse** [comment]
I am not familiar with what "injected unconditional" means in terms if the difference in `:Staging/standard`, but having that enabled for `adi` would seem like a far more consistent and sensible approach than `repo_checker` checking that. I can double check my notes, but I remember that functionality being there, but source checker bot and rpmlint both check the license as well so having a third place seemed a bit crazy. Additionally, it required a lot more API calls to fetch the `rpmlint.log` which seemed like a lot of needless waste. I believe it was in my write-up in the PR.

Anyway, if you point me to how it is done for letter stagings I can did into figuring out if/how we can make it work for adi. Otherwise, perhaps having the source checker bot which already looks at license would be a good alternative.

**Comment by jberry-suse** [comment]
I see the following in `openSUSE:Factory` `prjconf`, but assume this is not it?

```spec
%if "%_project" == "openSUSE:Factory" || "%_project" == "openSUSE:Factory:PowerPC" || "%_project" == "openSUSE:Factory:ARM" || "%_project" == "openSUSE:Factory:Rebuild" || "%_project" == "openSUSE:Factory:Live" || "%_project" == "openSUSE:Factory:NonFree"
#Support: brp-trim-desktopfiles
Support: rpmlint-Factory-strict
%endif
```

**Comment by jberry-suse** [comment]
Create PR do do just that. Alternatively, one could change the setup to create a `:Staging:adi` project which has this that all of them could build against that is a pure passthru for Factory, but contains the `prjconf` additions.

I created https://build.opensuse.org/project/prjconf/openSUSE:Factory:Staging:adi:22 using the tweaked code which works as intended. Assuming that will cause the right behavior in rpmlint then seems like a much better solution to looking in `rpmlint.log`.

**Comment by jberry-suse** [comment]
Indeed, and no need to do so. Either mirror the `:Staging` setup with `:Staging:adi` passthru for all adis or the simple `prjconf` addition provided in the PR.

On a different note, why does the license digger not handle this?

**Comment by jberry-suse** [comment]
Otherwise, not sure the order that the prjconf are evaluated and if one could set a variable to on adi's that could be picked up to then enabling staging related stuff.

**Comment by coolo** [comment]
I would prefer what you refer to as passthru - because that makes it easier to force project config changes to all of them in one go without having to rely on all staging managers to update their code.

**Comment by jberry-suse** [comment]
I agree, any opposition? Otherwise, I imagine the PR just need to modify the XML used to create adi projects and the new passthru project created. From what I understand the creation of new products on OBS with all the relevant parts is not found anywhere in this repository and as such cannot be updated to include this. Are there scripts somewhere?

**Comment by jberry-suse** [comment]
Alright, I created [`openSUSE:Factory:Staging:adi`](https://build.opensuse.org/project/prjconf/openSUSE:Factory:Staging:adi) which contains the following in`prjconf`:

```
Support: rpmlint-Factory-strict
```

The following repo setup:

```xml
  <build>
    <disable/>
  </build>
  <publish>
    <disable/>
  </publish>
  <debuginfo>
    <enable/>
  </debuginfo>
  <repository name="standard">
    <path project="openSUSE:Factory" repository="standard"/>
    <arch>x86_64</arch>
  </repository>
```

Which mirrors normal `adi` except for build disabled. Then I changed `adi:19`, which has one of my requests, to use the new `adi` as a passthru.

```xml
  <repository name="standard">
    <path project="openSUSE:Factory:Staging:adi" repository="standard"/>
    <arch>x86_64</arch>
  </repository>
```

The build log before installed `[109/109]` and after `[110/110]` which included our friend the `-strict` package.

I'll go ahead and create a PR which will generate `adi` stagings in this manor, but this means the `Staging:adi` project will need to be created for the 15s.

**Comment by jberry-suse** [comment]
Removed `<arch>x86_64</arch>` from `Staging:adi` to mirror `:Staging` since `arch` is required in individual `adi`s anyway.

**Comment by jberry-suse** [comment]
Does this make license checks like the following duplicate?

https://github.com/openSUSE/osc-plugin-factory/blob/ed70089adfa3acdd77e447460f4d903f992d2dcb/check_source.pl#L97-L103

I've also seen the invalid license split out, presumably by the source checks.

**Comment by nilxam** [comment]
`openSUSE:Factory:Staging:adi` project is culprit breaks dashboard api in https://github.com/openSUSE/obs_factory/blob/master/app/models/obs_factory/staging_project.rb#L116 , I removed `openSUSE:Factory:Staging:adi` project for now otherwise we get error 500.

**Comment by jberry-suse** [comment]
Well, shall I change `obs_factory`, locate the project somewhere to avoid the issue, or potentially just use the `:Staging` project as passthru since it already has conditional for letter only stagings and likely make the most sense?

I figured this would likely break something brittle, but a quick grep of `osc-plugin-factory` seemed ok. Alas `obs_factory` :(

**Comment by coolo** [comment]
I don't think there is a problem with building against :Staging

**Comment by coolo** [comment]
what's good enough for ring packages, should be fine for non-rings

**Comment by jberry-suse** [comment]
Was more a question of needed a separate config, otherwise I am extremely curious why it has not been this way all along. @DimStar77 just to confirm you are not aware of any reason?

**Comment by DimStar77** [comment]
> Was more a question of needed a separate config, otherwise I am extremely curious why it has not been this way all along. @DimStar77 just to confirm you are not aware of any reason?

There was simply no need to have a different config - pretty much everything inprjconf is not wrapped into conditions... using :Staging for adi to also get the rpmlint-Factory-strict into adi sounds reasonable

**Comment by jberry-suse** [comment]
I meant more a question of why it was not setup that way when `Support: rpmlint-Factory-strict` was added or similar rather than adding code for 3 different bots check. I updated PR to use it.

**Comment by jberry-suse** [comment]
I tested this on `adi:3` and it became unresolveable:

```
nothing provides gcc-c++, nothing provides pkgconfig, nothing provides rpm-build, nothing provides gcc-PIE
```

The rings are in the progress of building, so that may be an unwanted side effect of using `:Staging`. An alternative (short of different project) could be to create another repo without bootstrap setup in `:Staging` and link to that.

**Comment by DimStar77** [comment]
? building against openSUSE:Factory:Staging/standard should not care at all for the rings, as it will basically do

openSUSE:Factory/ports

you need openSUSE:Factory:Staging as a path NEXT to openSUSE:Factory/standard

**Comment by jberry-suse** [comment]
Yeah, that was my thought. Updated PR to do that.

**Comment by DimStar77** [comment]
I setup adi:3 to show the setup - seems to work
