### ISSUE TITLE
adi: fails to delete project and repeatedly triggers empty accepted comments

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1142]
Two parts:

1) the failure to delete project seems like OBS issue, but need to debug
2) the empty comments should be avoided in general as they can occur when a request is revoked, unselected and adi left empty

An example, is `adi:40` in Factory:

![image](https://user-images.githubusercontent.com/22943929/30612649-ea24def0-9d4a-11e7-9941-37c8560d9ce8.png)

**Comment by jberry-suse** [comment]
When `adi` command is run with `-d` the following can be seen.

```
CACHE_GET https://api.opensuse.org/group/factory-staging
adi:40 ready
POST https://api.opensuse.org/comments/project/openSUSE:Factory:Staging:adi:40
DELETE https://api.opensuse.org/source/openSUSE:Factory:Staging:adi:40
HTTP Error 400: Bad Request
```

**Comment by jberry-suse** [comment]
When issued manually a more detailed message explains why OBS will not remove.

```
osc -d api -X DELETE '/source/openSUSE:Factory:Staging:adi:40'
DELETE https://api.opensuse.org/source/openSUSE:Factory:Staging:adi:40
Server returned an error: HTTP Error 400: Bad Request
Date: Tue, 19 Sep 2017 20:00:55 GMT
Server: Apache/2.4.23 (Linux/SUSE)
Strict-Transport-Security: max-age=31536000
Cache-Control: no-cache
Vary: Accept-Encoding
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":1.2962969485670328,"db":35.343729,"backend":0,"xml":0}
X-Request-Id: 2d1f461f-7efd-478b-b30c-bc3ce41fb1c6
X-Opensuse-APIVersion: 2.8.51.git20170918T111141.9ef632b05
X-Runtime: 0.083271
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Opensuse-Errorcode: repo_dependency
X-Powered-By: Phusion Passenger 5.0.30
Status: 400 Bad Request
Content-Type: application/xml; charset=utf-8
Connection: close
Transfer-Encoding: chunked

<status code="repo_dependency">
  <summary>Unable to delete repository; following repositories depend on this project:
home:thipp:branches:openSUSE:Factory:Staging:adi:40/standard</summary>
</status>

Unable to delete repository; following repositories depend on this project:
home:thipp:branches:openSUSE:Factory:Staging:adi:40/standard
```

This we have seen before, not sure if we should come up with a solution

**Comment by jberry-suse** [comment]
Created https://build.opensuse.org/request/show/527377 to ask for removal of linking project.

**Comment by DimStar77** [comment]
We can't avoid users branching from an adi while they want to fix things - we should 'force delete' the adi: when we want to dispose of it (osc rdelete -f $prj); this breaks the branch of the user, but that's not what we should care for at this point (It's broken anyway, as the link the user has is pointing to a non-existing package)

**Comment by nilxam** [comment]
I second that force delete the adi when things was done there.
