### ISSUE TITLE
adi: *force* project deletion to handle branched references

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1144]
See #1142. Such requests could automatically be issued and is probably the only reasonable automated approach since it still allows for human sign-off.

**Comment by DimStar77** [comment]
I think it's over complex to send requests around on OBS and 'expect somebody to act'; just force delete the adi; the branch is broken already and the user did not care;

at best: make this an 'addon' to forcibly removing it, giving the user an additional headsup
