### ISSUE TITLE
Provide command to display virtually accepted delete requests

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1164]
Per closing of [poo#20420](https://progress.opensuse.org/issues/20420) @nilxam noted providing a command to view requests in the intermediate state would be useful.

**Comment by lnussel** [comment]
Dominique mentioned there might be loophole in the process where a delete request gets revoked but the target package stays disabled. so a consistency check might be useful

**Comment by nilxam** [comment]
> Dominique mentioned there might be a loophole in the process where a delete request gets revoked but the target package stays disabled. so a consistency check might be useful

Actually the better option IMO is like what I wrote in https://wiki.microfocus.net/index.php?title=SLE15_obs_feature_wishlist

<pre>
for better delete request handling, can we have an approach to "lock" a request, ie. the request's state can not change, but allowed to change the state only for target maintainer (background information: https://etherpad.opensuse.org/p/del-req-process)
</pre>

**Comment by jberry-suse** [comment]
Locking does sound better.

**Comment by DimStar77** [comment]
> Locking does sound better.

without any doubt - but until OBS implements that we might work on SLE16 or later

**Comment by jberry-suse** [comment]
hehe, fair enough

**Comment by jberry-suse** [comment]
Seems like this is fixed.
