### ISSUE TITLE
pkglistgen: producing invalid kiwi package list in Leap:15.0 stagings

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1212]
From `000product/openSUSE-dvd5-dvd-x86_64.kiwi` in stagings:

```
<repopackage name=" patterns-base-x86 [x86_64] not found on x86_64"/>
```

From `000product/openSUSE-dvd5-dvd-x86_64.kiwi` in stagings:**DVD**:

```
<repopackage name=" openSUSE-release-dvd not found on x86_64"/>
```

While also containing:

```
<repopackage name="openSUSE-release-dvd" addarch="x86_64"/>
```

**Comment by jberry-suse** [comment]
I fixed in all stagings to get things rolling.

**Comment by lnussel** [comment]
that is an error message from the package list generator. is has no other way to abort so it puts an invalid package name :) not sure what the problem with the pattern is. the missing release package is due to missing 000releaese-packages which is meant to be created by pkglistgen

**Comment by lnussel** [comment]
the error has vanished after the last checkin round

**Comment by jberry-suse** [comment]
Still seeing the `openSUSE-release-dvd` message in three of the stagings.
