### ISSUE TITLE
detect vanished 2nd spec file

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1232]
15.0 now had several cases where a 2nd spec file was removed from package. The local links in rings stayed though. We need some consistency check.

**Comment by nilxam** [comment]
we need to figure out https://github.com/openSUSE/open-build-service/issues/3948 first IMO, I saw webkitgtk3(as second specfile) was dropped from webkitgtk however OBS sees old revision was there thus webkitgtk3 built in ring2 still rather than a "excluded".
