### ISSUE TITLE
pkglistgen.sh depends on /usr/lib/obs/service/create_single_product but it cannot be found anywhere

### ISSUE THREAD

**Issue by lpechacek** [openSUSE/osc-plugin-factory#1237]
openSUSE-release-tools-pkglistgen package should introduce dependencies to get create_single_product installed.

**Comment by jberry-suse** [comment]
@lnussel as you or @coolo are familiar with the pkglistgen. Not sure how it is currently deployed, but perhaps add the service file while fixing up distribution stuff.

**Comment by lnussel** [comment]
it's not properly packaged yet. so far it runs locally. Needs to be moved to packagelists

**Comment by lnussel** [comment]
fixed in https://github.com/openSUSE/osc-plugin-factory/commit/205bed9c0bc8092f5650d918420918ed56d0eb70
