### ISSUE TITLE
leaper bot and factoryauto crashes due to Action instance has no attribute 'src_project'

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#1239]
while checking https://build.opensuse.org/request/show/538091 the leaper bot and factoryauto crashes due to 

<pre>
Nov 02 09:02:27 packagelists check_source[2731]: [I] checking 538091
Nov 02 09:02:29 packagelists check_source[2731]: [E] Action instance has no attribute 'src_project'
Nov 02 09:02:29 packagelists check_source[2731]: Traceback (most recent call last):
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 646, in runner
Nov 02 09:02:29 packagelists check_source[2731]:     workfunc()
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 614, in work
Nov 02 09:02:29 packagelists check_source[2731]:     self.checker.check_requests()
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 144, in check_requests
Nov 02 09:02:29 packagelists check_source[2731]:     good = self.check_one_request(req)
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 257, in check_one_request
Nov 02 09:02:29 packagelists check_source[2731]:     ret = func(req, a)
Nov 02 09:02:29 packagelists check_source[2731]:   File "/usr/local/bin/check_source", line 248, in check_action_delete
Nov 02 09:02:29 packagelists check_source[2731]:     self.maintbot.check_one_request(request)
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/check_maintenance_incidents.py", line 161, in check_one_request
Nov 02 09:02:29 packagelists check_source[2731]:     ret = ReviewBot.ReviewBot.check_one_request(self, req)
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/ReviewBot.py", line 257, in check_one_request
Nov 02 09:02:29 packagelists check_source[2731]:     ret = func(req, a)
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/check_maintenance_incidents.py", line 152, in check_action_delete
Nov 02 09:02:29 packagelists check_source[2731]:     self._check_maintainer_review_needed(req, a)
Nov 02 09:02:29 packagelists check_source[2731]:   File "/home/repochecker/src/osc-plugin-factory/check_maintenance_incidents.py", line 107, in _check_maintainer_review_need
Nov 02 09:02:29 packagelists check_source[2731]:     self.logger.debug("{} comes from {}, submitted from {}".format(pkgname, origin, a.src_project))
Nov 02 09:02:29 packagelists check_source[2731]: AttributeError: Action instance has no attribute 'src_project'
</pre>

**Comment by jberry-suse** [comment]
This code was introduced a year ago. Has this been crashing since then?

**Comment by nilxam** [comment]
In TW, none in my memory, but this issue occurs when a delete request to Leap.

**Comment by jberry-suse** [comment]
Ah, so likely when this code was invoked via `leaper` it was fine, but `factory-auto` being enabled recently triggers this. Alright that explains it.
