### ISSUE TITLE
Whitelisting request from SUSE:SLE-15:GA to Leap 15 in check_source

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#1264]
After submitted new package from SLE15 to Leap15, we see many request be declined due to download_file failed https://build.opensuse.org/request/show/543030 , upstream moved released source to different URL, we should disable check in check_source if the request is from SLE to Leap.

**Comment by DimStar77** [comment]
Probably we also want to skip the file download validation if a package comes from TW: at the time the package entered there, the file was published in this form on the mirrors

**Comment by nilxam** [comment]
FYI Discussed with @lnussel I've hot-patched http://susepaste.org/99851523 in packagelists for now.
