### ISSUE TITLE
staging plugin: EDITOR set to "/usr/bin/gvim -f" breaks --interactive

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/osc-plugin-factory#1271]
if EDITOR environment variable is set to "/usr/bin/gvim -f" (to make sure gvim call is blocking ), call to plugin with --interactive fails with "[Errno 2] No such file or directory"

**Comment by jberry-suse** [comment]
https://github.com/openSUSE/osc-plugin-factory/blob/b428ed3a7d54c8487710bded915a590bfcd79447/osc-staging.py#L599-L602

Ends up with:

```
["/usr/bin/gvim -f", temp.name]
```

Which obviously the first argument is indeed not a file.

Either need `EDITOR.split(' ') + [temp.name]` or `subprocess.call(' '.join([editor, temp.name), shell=True`)

**Comment by jberry-suse** [comment]
I am leading towards the first option.
