### ISSUE TITLE
adi staging: add i586 arch if there is a baselibs.conf

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#1304]
Especially for the case of wine: adi must build i586 so wine is completely installable, otherwise repo-checker will have to complain:

```
can't install wine-3.0~rc2-465.1.x86_64:
  nothing provides wine-32bit = 3.0~rc2 needed by wine-3.0~rc2-465.1.x86_64
can't install wine-nine-3.0~rc2-465.1.x86_64:
  nothing provides wine-nine-32bit = 3.0~rc2 needed by wine-nine-3.0~rc2-465.1.x86_64
```

IIRC, @jberry-suse already had this once patched and tested, but seems this was never pushed to git an activated for the bot? (I think we agreed then to enable i586 for everything that comes with a baselibs.conf)

**Comment by jberry-suse** [comment]
Yeah, it's local was going to submit with test, but ended up working on other things. I'll try and submit it.
