### ISSUE TITLE
TODO list for staging accept

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1324]
sometimes it's important to remember something for staging accept, e.g changing the rebuild mode, modifying the prjconf etc. Would be nice to have some way to store some free form text that is shown on accept.

**Comment by jberry-suse** [comment]
Could utilize `osc staging config`. Then modify `accept` to print the text of a given key if found. Perhaps allow multiple keys with a command prefix.

```
osc staging config todo Remember to do something important
```

```
osc staging config todo:afterthought Remember to do something else
```

Otherwise, just one key and use `--append` flag that already exists.
