### ISSUE TITLE
repo_checker: consider adding staging config option to skip cycle check

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1365]
It would seem to make sense to allow cycles to be _accepted_ at a staging level and thus allow the `repo-checker` to accept such reviews without having to do it manually or run `repo-checker` with the `--skip-cycle` flag. Perhaps `repo_checker-cycle-skip` or `repo_checker-cycle-accept`?

The usage would then be:

```
osc staging config A repo_checker-cycle-skip 1
```

**Comment by jberry-suse** [comment]
The added relevant being that the `repo-checker` has been soft-enabled for SLE and they do not have access to where the bot runs nor the user credentials so manually override will be even cumbersome.

On a related note this could also be acheived with group instead of user, but would still require manually (or tool assisted) accepting all the reviews. Having staging level inputs seems best as there are cases where cycles may exist along with real problems and the cycles are to be skipped, but the reviews not accepted until other problems resolved.

**Comment by lnussel** [comment]
I'd prefer a comment that the bot acts on. One reading the comment of repochecker is on that page in obs already anyways.

**Comment by DimStar77** [comment]
comments have the side effect that anybody can add them. The config is limited to be modified by staging masters (people having access to the prj meta)

**Comment by lnussel** [comment]
yes. the bots shouldn't listen to anybody :)

**Comment by jberry-suse** [comment]
Although we are really starting to blur the line between these two things (staging config and comments). If we keep it to only "review overrides" that applies to all bots I suppose that will be consistent. As such this depends on #1400 as it should use the same facility.
