### ISSUE TITLE
pkglistgen: use update repo also for drop list generator

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1396]
There are some python version updates in the update repos that end up having the same version in 42 as in 15. Due to the lp150 release prefix the 42 version is considered newer. Right now the droplist generator only looks at the GA repo where those python modules have a lower version still match the obsoletes tag of the corresponding packages in 15, so doesn't list them in obsoletepackages.inc.

**Comment by jberry-suse** [comment]
How should the update repos be handled? Merged on top of oss and non-oss, or separately in some fashion?

**Comment by lnussel** [comment]
or maybe merge oss, non-oss and oss:update, non-oss update. The latter pair would change all the time after all.
