### ISSUE TITLE
ReviewBot: allow review overrides via comments by staging masters

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1400]
via check_source_in_factory leaper has hardcoded logic to pass requests if they are only left waiting for openSUSE:Factory:Staging:*. This should be configurable to be able to also skip for e.g. repochecker.

**Comment by jberry-suse** [comment]
8 levels of nesting with 3 loops...scary just describing it.

**Comment by jberry-suse** [comment]
What is the intended case here. Allow any reviews that are always present (like `quick` strategy does)? Perhaps just share that code which white lists project reviewers.

**Comment by jberry-suse** [comment]
Given a request can be denied on account of `repo-checker` it seems questionable to have `leaper` approve it.

**Comment by lnussel** [comment]
leaper needs refactoring, no doubt about that :) Also, the functions called in other bots would be better suited in the ReviewBot base class.

There's always a chance that requests get declined on either side. Assuming that this is the exception we'd approve the request in good faith. That is already done by ignoring the staging project review. Due to deadline SLE may sometimes weight the pros and cons of accepting a request differently than Factory anyways.

The feature requested has an overlap to some degree with https://github.com/openSUSE/osc-plugin-factory/issues/1397 ie if there's an easy way to tell the bot to override the result there may be no need to hardcode skipping certain reviews.

**Comment by jberry-suse** [comment]
Seems like that's back to the discussion about using a group vs user for review. As then staging masters could override the reviews of bots in OBS instead of needing to add some functionality to the bot.

**Comment by coolo** [comment]
yeah, I guess it's fair to say that groups as factory-auto or leaper have failed. Especially in the light of https://github.com/openSUSE/open-build-service/issues/2923

**Comment by jberry-suse** [comment]
Alright, so we'll workaround OBS lacking the functionality via comment instructions to bots that are only valid from users within staging group per `conf.py`?

**Comment by lnussel** [comment]
missed the question :/ Whether or not we call it a workaround doesn't really matter. I think the comment method is just convenient as it doesn't  require switching back and forth between web ui and cli.

**Comment by lnussel** [comment]
hmm, we didn't cover the configurable part yet. Especially since comments do not reflect the real reason why leaper waits for something (eg leaper says it's waiting for legal-auto where it's waiting for repo-checker), plus SLE has repo-checker itself now. I think we should still implement configuration for this:
https://github.com/openSUSE/osc-plugin-factory/blob/master/check_source_in_factory.py#L184

**Comment by lnussel** [comment]
probably makes sense to refactor _check_requests into ReviewBot

**Comment by lnussel** [comment]
or maybe make the function return the reviewers and let the caller decide

**Comment by jberry-suse** [comment]
Since this morphed into comment overrides which works I'll break it off.
