### ISSUE TITLE
repo_checker: cannot rely on whatdependson for i586

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1408]
See https://github.com/openSUSE/open-build-service/issues/4515

The whatdependson information from OBS is unreliable. Depending on the outcome of the aforementioned issue, repochecker may have to walk the list of dependencies itself and double check :/

**Comment by jberry-suse** [comment]
I mean....what's the point of OBS if we re-create half it's features in this repo and continue to increase the number.

**Comment by nilxam** [comment]
IMHO we should just ignore i586' whatdependson result in r-c for Leap since we did not enabled all package builds on i586.

**Comment by lnussel** [comment]
we still have the -32bit packages that need to be checked though. I agree that adding workaround suck obviously. not sure how often this happens either. Maybe just a glitch we can work around manually every once in a while.
