### ISSUE TITLE
leaper: dear bot, don't take yourself so important

### ISSUE THREAD

**Issue by coolo** [openSUSE/osc-plugin-factory#1422]
```
Visit https://build.suse.de/request/show/156275

Leap Reviewbot wrote in request 156275:

unhandled request type set_bugowner
```

Why does it have to notify me it didn't do anything?

**Comment by jberry-suse** [comment]
This would be another example of a _report_ that would be preferred if no notification would be sent. The report being there provides an explanation of the bot's behavior, but as you suggest is not relevant for notification. This simply exposes the fact that OBS does not provide the facilities needed for the bots in one way or another. Leaper could be changed to avoid comments in such instances, but just further avoiding the problem.

**Comment by coolo** [comment]
well, the bot has the review accept message to put that in - this is not a comment, this is a review message.

**Comment by lnussel** [comment]
log messages get collected and redirected to the comment. That is just the default mechanism of any bot. just adding an explicit handler for bugowner request that does not log fixes this.

**Comment by jberry-suse** [comment]
> well, the bot has the review accept message to put that in - this is not a comment, this is a review message.

In this instance since the output is short yes, but in general the lack of such a feature is the root problem.

> log messages get collected and redirected to the comment. That is just the default mechanism of any bot. just adding an explicit handler for bugowner request that does not log fixes this.

Yes, disabling comment for default handler should be simple.

**Comment by jberry-suse** [comment]
After the last refactoring the code in question is:

https://github.com/openSUSE/osc-plugin-factory/blob/bac6644c6f847d40ea921ae49312794db26da84a/ReviewBot.py#L299-L303
