### ISSUE TITLE
Can't use for casp 

### ISSUE THREAD

**Issue by coolo** [openSUSE/osc-plugin-factory#1428]
When I try just list requests for casp, it won't work as it defaults for SUSE:* to sle-staging-manager (and doesn't check the dashboard config)

So I add a section into my oscrc:
[SUSE:SLE-12-SP3:Update:Products:CASP30]
staging-group=caasp-staging-managers

and then it explodes:
```
  File "/suse/coolo/.osc-plugins/osc-staging.py", line 410, in do_staging
    config = Config(opts.project)
  File "/suse/coolo/.osc-plugins/osclib/conf.py", line 178, in __init__
    self.populate_conf()
  File "/suse/coolo/.osc-plugins/osclib/conf.py", line 207, in populate_conf
    conf.config[self.project] = self.read_section(self.project, defaults)
  File "/suse/coolo/.osc-plugins/osclib/conf.py", line 225, in read_section
    return dict(cp.items(section))
  File "/usr/lib64/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib64/python2.7/ConfigParser.py", line 663, in _interpolate
    if value and "%(" in value:
TypeError: argument of type 'int' is not iterable
```

I know that the priority field in osclib/conf.py is the problem - and it works if I add a raw=True into the cp.items call. But I don't know what is the proper solution

**Comment by jberry-suse** [comment]
As for the `staging-group` not being picked up from remote config, the way `StagingAPI` was designed it loads all values immediately which does not work for remote config which can only be loaded after `StagingAPI` is available. When developing I assumed that core values such as that should not be changed on a regular basis and as such should be fine if left that way. If desired those fields could be set to lazy load as `nocleanup-packages` was.

**Comment by coolo** [comment]
the value of this is not changed often, no - but we introduce new projects with new groups more often than you think :)
