### ISSUE TITLE
pkglistgen: create_single_product failing due to unknown element 'NULL'

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#1437]
```
FAILED: Unable to parse /home/jberry/.cache/opensuse-packagelists/api.opensuse.org/openSUSE:Leap:15.0/000product/openSUSE.product: unknown element 'NULL'
```

Determined to be in `obsoletepackages.inc`:

```xml
<!-- openSUSE-15.0-x86_64-Build153.1 -->
<obsoletepackage><NULL></obsoletepackage>
```

included via:

```xml
<xi:include href="obsoletepackages.inc" />
```

The build is fairly recent which is how it was introduced so should be a matter of determining why pkglistgen creates a `NULL` and avoiding it.

**Comment by jberry-suse** [comment]
I am somewhat curious if that is standard XML representation for `NULL` as it seems like the perl parser doesn't like it in general.

**Comment by lnussel** [comment]
looks like a short download. We should verify the checksum to make sure the metadata download is complete:
https://github.com/openSUSE/osc-plugin-factory/blob/master/pkglistgen.py#L907

**Comment by jberry-suse** [comment]
Interestingly, the resulting solv file when done manually via:

```
wget http://download.opensuse.org/distribution/leap/15.0/repo/oss/repodata/c1daf3ffbe079c7b6407ddf09696b46af8be451dbb8c29983edeef9d944048fa-primary.xml.gz
zcat repodata/c1daf3ffbe079c7b6407ddf09696b46af8be451dbb8c29983edeef9d944048fa-primary.xml.gz | rpmmd2solv > x.solv
```

produces a `0.2MB` smaller file that when used in-place of the one create by `do_dump_solv` make `pkglistgen` happy.

As such this is either something to do with `do_dump_solv` code which has to be rather interesting given it only breaks on this build...or something fun with python gzip code perhaps a bug there.

**Comment by jberry-suse** [comment]
Long-story short. I implemented the checksum and the gzip data python receives via `requests` (http) is correct, but the ungzipped output is short.

Last entry from manual method:
```xml
<package type="rpm">
  <name>zziplib-devel-32bit</name>
  <arch>x86_64</arch>
  <version epoch="0" ver="0.13.67" rel="lp150.2.1"/>
  <checksum type="sha256" pkgid="YES">a04be42d731be56ac571c1726e8f6de1e3002345ef9242147dc978336c12166f</checksum>
  <summary>Free zip compression library with easy to use API</summary>
  <description>That are the header files needed for developing applications using
ZZipLib.</description>
  <packager>https://bugs.opensuse.org</packager>
  <url>http://zziplib.sourceforge.net</url>
  <time file="1519234648" build="1517918400"/>
  <size package="11656" installed="0" archive="788"/>
  <location href="x86_64/zziplib-devel-32bit-0.13.67-lp150.2.1.x86_64.rpm"/>
  <format>
    <rpm:license>LGPL-2.1+</rpm:license>
    <rpm:vendor>openSUSE</rpm:vendor>
    <rpm:group>Development/Libraries/C and C++</rpm:group>
    <rpm:buildhost>lamb14</rpm:buildhost>
    <rpm:sourcerpm>zziplib-0.13.67-lp150.2.1.src.rpm</rpm:sourcerpm>
    <rpm:header-range start="5096" end="11408"/>
    <rpm:provides>
      <rpm:entry name="zziplib-devel-32bit" flags="EQ" epoch="0" ver="0.13.67" rel="lp150.2.1"/>
      <rpm:entry name="zziplib-devel-32bit(x86-32)" flags="EQ" epoch="0" ver="0.13.67" rel="lp150.2.1"/>
    </rpm:provides>
    <rpm:requires>
      <rpm:entry name="libzzip-0-13-32bit" flags="EQ" epoch="0" ver="0.13.67"/>
      <rpm:entry name="zziplib-devel" flags="EQ" epoch="0" ver="0.13.67"/>
    </rpm:requires>
  </format>
</package>
</metadata>
```

vs the last entry from python:

```xml
<package type="rpm">
  <name>z
```

**Comment by jberry-suse** [comment]
Interestingly, the files are also completely different sizes. Python creates 331MB file vs manual is 82MB.

**Comment by jberry-suse** [comment]
The number of package entries varies enourmously:

- 142997: python
- 35750: zcat

**Comment by jberry-suse** [comment]
Resolved by adding `f.flush()`. It seems this build hit some underlying buffer sizes. :) Thankfully `git blame` points to another. ;)

**Comment by jberry-suse** [comment]
Realistically:

- libsolv (python bindings) should have complained about invalid XML since the file just ended and left >= 2 tags unclosed not to mention an incomplete entry
- mergesolv could have also noticed the NULL entry

As a result:

- pkglistegen read in `<NULL>` and dumped into `obsoletepackages.inc`
- `create_single_product` didn't like the bogus XML tag `<NULL>`

Had it been caught right away by libsolv this would have been a _LOT_ easy to figure out.

**Comment by jberry-suse** [comment]
Deployed in production from my forked version of `pkglistegen.py` and it produced

https://build.opensuse.org/package/rdiff/openSUSE:Leap:15.0/000product?linkrev=base&rev=158

which includes:

```diff
@@ -581,6 +583,10 @@
   <obsoletepackage>yast2-trans-sr-Latn</obsoletepackage>
 <!-- openSUSE-15.0-x86_64-Build151.1 -->
   <obsoletepackage>libgsoap-2_8_62</obsoletepackage>
+<!-- openSUSE-15.0-x86_64-Build153.1 -->
+  <obsoletepackage>libphobos2-0_78</obsoletepackage>
+  <obsoletepackage>libretro-gtk-0_14</obsoletepackage>
+  <obsoletepackage>typelib-1_0-Retro-0_14</obsoletepackage>
 <!-- openSUSE-42.1-x86_64-Build0265 -->
   <obsoletepackage>LibVNCServer</obsoletepackage>
   <obsoletepackage>Qrosspython-devel</obsoletepackage>
```

ie the troublesome build.
