### ISSUE TITLE
  Package with existing license declined 

### ISSUE THREAD

**Issue by rombert** [openSUSE/osc-plugin-factory#415]
I have recently submitted [SR #329513](https://build.opensuse.org/request/show/329513) for the icinga2 package and factory-auto declined with the following message:
 
> icinga2.spec does not appear to contain a Copyright comment. Please stick to the format
>  
>  # Copyright (c) 2011 Stephan Kulow
>  
>  or use osc service localrun format_spec_file

The spec file is shared with upstream and contains a copyright statement

    # * Copyright (C) 2012-2015 Icinga Development Team (http://www.icinga.org)    *

Can the script be adjusted to accept this form of copyright header as well?

( Originally reported at openSUSE/obs-service-source_validator#24 )

**Comment by aplanas** [comment]
Uhm I think that is this `*` at the beginning of your copytight statement:

https://github.com/openSUSE/osc-plugin-factory/blob/master/source-checker.pl#L49

**Comment by rombert** [comment]
Yes, precisely. That's the way upstream has it and we try to use it unchanged. It is still valid syntax, though

**Comment by aplanas** [comment]
Well, https://github.com/openSUSE/osc-plugin-factory/pull/416 is there, lets see if is in conformance with current policies.

**Comment by rombert** [comment]
Great, thank you
