### ISSUE TITLE
factory-repo-chcecker check instal deps agains't wrong package, if is linked to abi..

### ISSUE THREAD

**Issue by mimi1vx** [openSUSE/osc-plugin-factory#457]
for example, pandoc has dependency on ghc-pandoc-types and texmath + texmath has also dependency on ghc-pandoc-types

If is together version bumped pandoc and ghc-pandoc-types, it needs link texmath to adi with this packages,

build passes but "factory-repo-checker"  fails with:

```
Can't install ghc-pandoc-1.16.0.2-23.2.x86_64:
nothing provides libHStexmath-0.8.4.1-6VS2lNf5TI8E9QXTN4FwWr-ghc7.10.3.so()(64bit) needed by ghc-pandoc-1.16.0.2-23.2.x86_64
```

--> it use to check texmath from openSUSE:Factory repo and not adi's own

**Comment by jberry-suse** [comment]
Should be resolved by #964.
