### ISSUE TITLE
staging api: don't fill packages_staged in _init_

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#463]
stagingapi is used by totest manager. Unfortunately stagingapi calls `_get_staged_requests()` which is rather lengthy without actual need for it. packages_staged shouldn't be initialized in `_init_` but only when it's actually needed.

**Comment by jberry-suse** [comment]
This appears to have been accomplished already in 28831300fc515e200aea1e45567a60efdd891802.
