### ISSUE TITLE
RED: staging list crashes on IBS

### ISSUE THREAD

**Issue by coolo** [openSUSE/osc-plugin-factory#534]
There is an hardcoded openSUSE:Factory in the list command that breaks heavily when trying to staging list for SP2

**Comment by nilxam** [comment]
I guess https://github.com/openSUSE/osc-plugin-factory/commit/4c43fe5c87636ef1dc0890e548563f5bca96079f causes the crash, will fix it tmr.

**Comment by nilxam** [comment]
hmm...I've go through the change, and it should shows an ugly layout with '00' string in the output rather than a real crash AFAICS,do you really seen an crash?

**Comment by coolo** [comment]
b505e7e7d87c09368ab1a44b373b7df1823a1ce4 is the fix for that - I didn't run master at the point of crash
