### ISSUE TITLE
Invalid URL in decline text

### ISSUE THREAD

**Issue by cboltz** [openSUSE/osc-plugin-factory#564]
https://build.opensuse.org/request/show/423555 was declined by factory-auto (that's correct - I accidently submitted from the project instead of the package).

However, the decline message comes with an invalid URL:

  2 actions in one SR is not supported - https://github.com/openSUSE/osc-plugin-factory/fork_select

.../fork_select only results in a 404 not found error. Please fix the description or (re?)create the file.

(CC @ccboltz)

**Comment by DimStar77** [comment]
'fork_select' used to be a nice github feature that 'forked the project' - We'll need to get to a nice link indeed

**Comment by jberry-suse** [comment]
This link was removed when ported in 8db3461a00784e999cb3218c70d16a10b2e70f38
