### ISSUE TITLE
osclib/update_status_comments: put link to staging dashboard

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#573]
put link to staging dashboard in comment, eg.
https://build.opensuse.org/project/staging_projects/openSUSE:Leap:42.2/adi:84

helps to get an overview if there are many packages

**Comment by shyukri** [comment]
This link triggers 500 error on OBS.

**Comment by lnussel** [comment]
the adi projects are dynamic. just try a number that exists :)

**Comment by lnussel** [comment]
ah, and 42.2 is done. so try Factory or 42.3
