### ISSUE TITLE
use systemd journal module for logging

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#652]
In some cases it may be desirable to optionally let a bot log to the journal itself explicitly, eg in addition to tty if the bot is running in screen/tmux

http://stackoverflow.com/questions/34588421/how-to-log-to-journald-systemd-via-python

**Comment by jberry-suse** [comment]
I vaguely remember someone indicated that the bots all run under systemd now. Is that correct and if so is this still relevant?

**Comment by lnussel** [comment]
yes, systemd puts stdout to the journal. Not sure anymore if we get additional benefits by logging ourselves.

**Comment by jberry-suse** [comment]
I'm not aware of any if already running directly under systemd.

**Comment by lnussel** [comment]
closing for now
