### ISSUE TITLE
Investigate update_crawler.py creating duplicate requests

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#699]
A few times I have seen leaper requests that are identical to requests already submitted, but not yet accepted. A recent example.

- cargo
  - https://build.opensuse.org/request/show/458554 (leaper)
  - https://build.opensuse.org/request/show/457244 (original)

- rust
  - https://build.opensuse.org/request/show/458553 (leaper)
  - https://build.opensuse.org/request/show/457245 (original)

It would seem this is undesirable.

**Comment by DimStar77** [comment]
same problem as https://github.com/openSUSE/obs-autosubmit/issues/1 - which already has some description for you

**Comment by jberry-suse** [comment]
Will re-open if reappears.
