### ISSUE TITLE
fix stale lock files

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#709]
sometimes the locking goes wrong and a stale lock prevents further work. We either need an unlock command to force unlock or have e.g. a --force-lock command to ignore an existing lock, especially when it is from the same user as the calling one.

**Comment by DimStar77** [comment]
so, osc staging unlock would 'just' be calling ``osc meta attribute openSUSE:Factory:Staging --attribute openSUSE:LockedBy --delete``` ?

**Comment by lnussel** [comment]
I always used osc api -X DELETE .. :-) but yes, a more obvious way for the less technical users was needed
