### ISSUE TITLE
[bug] investigate accept notification with empty package list

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#752]
I received the following notification in regards to KDE:Applications staging.

```
Dominique Leuenberger wrote in project openSUSE:Factory:Staging:H:

Project "openSUSE:Factory:Staging:H" accepted. The following packages have been submitted to openSUSE:Factory: .
```

Looking at the code in `accept_command.py`:

```python
packages = []
for req in meta['requests']:
    packages.append(req['package'])

pkg_list = ", ".join(packages)
cmmt = 'Project "{}" accepted.' \
        ' The following packages have been submitted to {}: {}.'.format(project,
                                                                        self.api.project,
                                                                        pkg_list)
```

It would seem that would not be able to occur. Given the package list was rather large perhaps OBS chops it off?

**Comment by DimStar77** [comment]
That's not a bug - but a 'feature' - I force accepted a staging that was already accepted (the last thing was going wrong and I still wanted to have the cleanup done properly)

**Comment by jberry-suse** [comment]
Well that makes me feel a bit better since there is not a clear explanation looking at the code.
