### ISSUE TITLE
cleanup_rings whitelist

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#759]
we need a list of packages cleanup_rings should not touch.

candidates:
* kernel-syms
* gnome-music

**Comment by lnussel** [comment]
there are some cases where multi-spec packages are in different rings though

**Comment by DimStar77** [comment]
and the split across rings is something we live from - just there nobody/nothing cares about the rebuild counters - which makes the kernel the odd one out

**Comment by nilxam** [comment]
plus

- python3-request : requirement of gnome-music
- python3-py : build requirement of python3-request

**Comment by jberry-suse** [comment]
Seems like the biggest downfall of the tool is that it checks `BuildRequires` and only `Requires` for the DVD image. It would likely make the tool slower, but it would seem appropriate to check runtime requirements as that seems to be the common issue in a number of the cases listed.
