### ISSUE TITLE
Superseded request is still show on the list until next run

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#780]
With refactored supersede logic, `osc staging list --supersede` did superseding request correctly, however the superseded request will still show on the list. Note: next run it disappears.

**Comment by jberry-suse** [comment]
Interesting. To be sure I'm clear the appearing in the list even when superseded is a new occurrence? I only changed the conditions about when to supersede so I would not expect that to change what shows up in the list.

**Comment by jberry-suse** [comment]
Turned out to be the caching of existing calls. Rather than drop the caching, which reduced the number of calls if nothing is superseded by one, I added an invalidate.
