### ISSUE TITLE
Investigate leaper recreating requests when superseded, but not yet accepted

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#791]
Not sure if this is related to the new workflow which marks requests as ignored (if difference source hash and source project) and then @lnussel manually superseded after making a decision or if this is related to #699.

Two examples of a cool tipple. :) 

cabal-rpm

- https://build.opensuse.org/request/show/486179
- https://build.opensuse.org/request/show/485985
- https://build.opensuse.org/request/show/485382

alex

- https://build.opensuse.org/request/show/485986
- https://build.opensuse.org/request/show/485381
- https://build.opensuse.org/request/show/486178

**Comment by lnussel** [comment]
The case is not handled I guess
https://github.com/openSUSE/osc-plugin-factory/blob/master/update_crawler.py#L152
