### ISSUE TITLE
Consider patched/updated systemd on packagelists to not strip leading whitepsace in logs

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#799]
I imagine this is unlikely to happen, but figure it might be worth a discussion. The staging-bot logs are rather ugly given that the leading whitespace is stripped (an issue I had when first running them locally), but systemd has since changed this behavior, https://github.com/systemd/systemd/pull/156, and the TW version works as expected. Not sure if worth considering either a infra package that is patched or even SP3. The current behavior is a tad annoying.

**Comment by lnussel** [comment]
systemd isn't updated in SP3. Feel free to open a bug report and ask for a backport though :)

**Comment by jberry-suse** [comment]
Filed bsc#1033855.

**Comment by jberry-suse** [comment]
According to maintainers the change was already backported and at this point SP2 should be using the upstream version containing the change. I double checked version on the machine and sources for SP2 and all seem to indicate it should not be stripping whitespace, but yet it does. Hmm.

**Comment by jberry-suse** [comment]
Fix accepted and presumably we come down in an update.

Before:
```
Apr 21 19:45:06 ip-172-30-0-203 systemd[1]: Starting padded...
Apr 21 19:45:06 ip-172-30-0-203 env[12382]: no padding
Apr 21 19:45:06 ip-172-30-0-203 env[12382]: two spaces
Apr 21 19:45:06 ip-172-30-0-203 env[12382]: - four spaces
Apr 21 19:45:06 ip-172-30-0-203 systemd[1]: Started padded.
```

After:
```
Apr 21 19:46:43 ip-172-30-0-203 systemd[1]: Starting padded...
Apr 21 19:46:43 ip-172-30-0-203 env[1659]: no padding
Apr 21 19:46:43 ip-172-30-0-203 env[1659]:   two spaces
Apr 21 19:46:43 ip-172-30-0-203 env[1659]:     - four spaces
Apr 21 19:46:43 ip-172-30-0-203 systemd[1]: Started padded.
```

Seems reasonable to close and re-open if this never ends up coming down in update.

**Comment by jberry-suse** [comment]
This update is now available. Any procedure that needs to be followed for updating packagelists machine?

**Comment by jberry-suse** [comment]
After discussing with @DimStar77 I deployed last week and have confirmed that the journal entries now have proper indentation!
