### ISSUE TITLE
supersede: does not update project comment

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#805]
The project meta is updated:
```yaml
- {author: Vogtinator, id: 487572, package: plasma5-desktop}
```

but not the comment:
```
Request#486836 for package plasma5-desktop submitted by @Vogtinator
```

Would likely make sense to have some user visible output indicating that id did something as well. Likely related to adding a supersede command as discussed for Leap which could then just be called by `list --supersede`, but share same output.

Would seem like supersede should put a request through the same code as doing a normal select so that this situation is avoided. Unless there is some reason not to update the comment and leave them inconsistent?

**Comment by nilxam** [comment]
yes, avoiding spamming all submitter in the same group, thus the project comment only updated when have new package added into the group or have package out the group. the comment is mainly put the group member in CC, then they can be noticed. after any new project comment created

**Comment by jberry-suse** [comment]
Alright then. Works as designed.
