### ISSUE TITLE
Consider enabling staging-bot for Factory

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#823]
I have resolved the shortcomings that were on my list before considering for Factory in addition to suggestions from @DimStar77. A few times I had run the other bits of the bot (minus select) which cleanup up obsolete requests, superseded, untracked, and adi work as expected. Undoubtedly more things that can be improved, but it seems like the major points are handled to do an good initial staging job and manage the mundane parts.

Given the bot also has a proper home and thus can be monitored and disabled as needed it seems appropriate to consider its usage for Factory.

From reviewing the `splitter_info` in Factory and feedback clearly the proposals are being tried and used. Are there any other blocking issues?

For reference, some of the recent changes relevant to Factory:

- #816: request_splitter: add super strategy for representing devel groups.
- #810: request_splitter: switch from build percentage to staging age for merge.
- #806: request_splitter: provide and utilize an aged attribute on requests.

The last two allow for a minimum of `55` minutes (less than two 30 min bot cycles) of time before a request will be staged by a none strategy which allows for patterns to be observed. The staging age allows for followup requests to be merged within an 8 hour window after staging was activated. The super groups being a request by dimstar.

If no objections, perhaps just enable it and disable if it becomes an issue. For those who are not aware the `staging-bot-regular@Factory` service on packagelists is the on in question as the `-daily` cleanup service is already enabled. The timer just needs to be enabled/started.

**Comment by nilxam** [comment]
I concern about cleanup "superseded" part, I guess it's related, see https://build.opensuse.org/request/show/486562 and https://build.opensuse.org/request/show/487431 , 486562 was staged and be superseded, before 487431 **superseded it in real* in the staging project, staging-bot removed 486562 from staging project, therefore the others python packages unable to build until select 487431 back to the same staging. this behavior is not good for Factory IMO.

**Comment by jberry-suse** [comment]
I am not sure I understand.

- 486562 staged in E
- 487431 created and supersedes 486562
- bot removes 486562 rather than supersede it?

The bot should just use `list --supersede` like normal to replace 486562 with 487431. The cleanup, `unselect --cleanup` gets the list from the staging dashboard. If that is not updated then perhaps a secondary check before unselecting needs to be performed to ensure it has not been superseded. Although that would seem unlikely since the request would have to be revoked/rejected first anyway to be considered obsolete and then superseded shortly there after in between all this happening.

Perhaps you can clarify what happened for me.

**Comment by nilxam** [comment]
IIRC 486562 was superseded by 487431, but no one use ``list --supersede`` in that period, ie. 487431 was not replaced 486562 in staging E in real. After that I see 486562 was removed from E(no package and also not in metadata, strangely also doesn't have unselect history in the request), 487431 of course in backlog.

**Comment by nilxam** [comment]
hmm...or someone changed that manually...

**Comment by jberry-suse** [comment]
Well if that was the bot it definitely is not desired. To be clear the bot itself runs `list --supersede` before running `unselect --cleanup`. I'm going to guess it hit an edge case where the supersede request came in during the middle of the bots process (if it was the bot) and that the dashboard indicates those requests are obsolete even if they can be superseded. If that is a possibility then `unselect --cleanup` should be possible to check for it. If it was the bot and that is possible I am impressed that during the ~3 times I ran it we hit that case as I would expect it to be rare. It seems packagelists does not keep logs very long otherwise I would be able to tell for certain.

The reason there is no unselect in the history is that it would have occurred after it was superseded. Once a request is declined or superseded OBS no longer allows review changes. As such the stagingapi stuff does not attempt to record anything since it would not be allowed. This is one of the things I ran into elsewhere that was annoying, but perhaps we should change the code to make a comment if the reviews cannot be changed so there is at least some record for humans.

**Comment by nilxam** [comment]
I just check that, yup, it probably running into this edge case,

``osc rdiff -M -c 10011 openSUSE:Factory:Staging:E`` is made by the bot.

**Comment by jberry-suse** [comment]
Alright, that issue should be resolved (pending merge). Anything else? :)

**Comment by jberry-suse** [comment]
bump

**Comment by DimStar77** [comment]
Discussed the matter with @jberry-suse over IRC: conclusion: we should go ahead and enable the bot in order to gain more experience with it (in order to fine-tune it as needed)

**Comment by jberry-suse** [comment]
enabled `staging-bot-regular@Factory.timer` post deployment of whitelist!

**Comment by DimStar77** [comment]
Note 1: the bot seems to be dropping 'declined' requests from the letter stagings; often this is not the right thing, as we expect a corrected submission to be incoming 'shortly' - and many times the group would depend on that fix (seen with the patterns-* in :F)

**Comment by jberry-suse** [comment]
Likely the only reliable fix then is to add a time window before removing. Alternatively #811 may provide a better fix, but will take longer to finish.

**Comment by nilxam** [comment]
Seriously people complained to me about https://build.opensuse.org/request/show/491760 , it was staged in :C but cleanup-ed after declined and now it was in :B by auto-selecting https://build.opensuse.org/request/show/491760

**Comment by nilxam** [comment]
and I can't do anything today due to http://susepaste.org/14244669 , I can't win the locking game. therefore I just disabled staging-bot-regular for now, I need to move some request...

**Comment by jberry-suse** [comment]
The obsolete cleanup is indeed to aggressive and should be disabled for the time being until we can agree on the workflow surrounding it. As with many things tackled by the bot a formal workflow definition did not exist so some experimentation is in order. Everything else works correctly over the weekend and did a bunch of good stuff. Unless there is something else, I would suggest simply disabling that bit for the time being.

As for the lock, looking at logs unless it hits a large load of things to do it takes < 2 minutes. It is unclear how often you are running those commands, but unless timed perfectly just wait a minute or two...just as one would if another person was working. I am curious what the `hold: Factory accept bot` one was unless someone was experimenting as that is not placed by anything in which I am familiar. Alternatively the interval can be increased...simple solutions.

**Comment by jberry-suse** [comment]
The `--wipe-cache` executes before the lock is acquired so it should need to be done each time. Once I complete the ring command which will tweak the project descriptions will only a delete is made (can be done manually until then) the caches should auto-clear when those changes are made. OBS unfortunately does not indicate a project was updated when a delete is made, hence the need for that.

**Comment by jberry-suse** [comment]
I would suggest looking for who may have run `osc staging lock -m "Factory accept bot"` as `staging-bot`. ;)

**Comment by nilxam** [comment]
> The --wipe-cache executes before the lock is acquired so it should not need to be done each time. Once I complete the ring command which will tweak the project descriptions will only a delete is made (can be done manually until then) the caches should auto-clear when those changes are made. OBS unfortunately does not indicate a project was updated when a delete is made, hence the need for that.

yeah, I know, I just repeating my previous command ``<up arrow>``+``<enter>`` :)

**Comment by nilxam** [comment]
I've no idea who runs that ``Factory accept bot`` lock and where, I never win the locking game in 2 hours, I have a longer record than http://susepaste.org/14244669

**Comment by DimStar77** [comment]
The factory bot was my machine - but it ran as my own user, NOT anything else (apparently the unlock in the script did not work though yesterday... this worked fine today though)

**Comment by jberry-suse** [comment]
The hold introduced by `lock` command remains for full `ttl`, which defaults to 1 hour, or until `unlock` is called. The fact that it showed up as `staging-bot` and was not released per @DimStar77 note makes me think something interesting happened. That is worth investigation, but was clearly not part of `staging-bot` operations.

**Comment by jberry-suse** [comment]
I found the relevant lines regarding @DimStar77's lock before it was authored as `staging-bot`.
```
May 02 09:20:25 packagelists systemd[1]: Starting staging-bot-regular for Factory...
May 02 09:20:27 packagelists staging-bot[15563]: Lock acquired by [dimstar_suse] 0:24:22.482430 ago, reason <hold: Factory accept bot>. Try
May 02 09:20:27 packagelists systemd[1]: staging-bot-regular@Factory.service: Main process exited, code=exited, status=255/n/a
May 02 09:20:27 packagelists systemd[1]: Failed to start staging-bot-regular for Factory.
May 02 09:20:27 packagelists systemd[1]: staging-bot-regular@Factory.service: Unit entered failed state.
May 02 09:20:27 packagelists systemd[1]: staging-bot-regular@Factory.service: Failed with result 'exit-code'.
May 02 09:50:56 packagelists systemd[1]: Starting staging-bot-regular for Factory...
May 02 09:50:56 packagelists staging-bot[26316]: Lock acquired by [dimstar_suse] 0:54:51.576411 ago, reason <hold: Factory accept bot>. Try
May 02 09:50:56 packagelists systemd[1]: staging-bot-regular@Factory.service: Main process exited, code=exited, status=255/n/a
May 02 09:50:56 packagelists systemd[1]: Failed to start staging-bot-regular for Factory.
May 02 09:50:56 packagelists systemd[1]: staging-bot-regular@Factory.service: Unit entered failed state.
May 02 09:50:56 packagelists systemd[1]: staging-bot-regular@Factory.service: Failed with result 'exit-code'.
```

I believe this is an new edge-case related to the hold functionality when it expires and lock is acquired by a different user. Tests for everything except this, so I'll go ahead and add one.

Long-story short.

- `dimstar_suse` ran `osc staging lock -m "Factory accept bot"`
- `staging-bot` tries twice during lock, but exits
- `staging-bot` runs again and lock is paste `ttl` and thus expired so the lock is overriden, but the hold portion is added to reason instead of fully clearing

Which is how that lock ended up being attributed to `staging-bot`.

**Comment by jberry-suse** [comment]
`staging-bot` has been enabled since Friday. If further issues either open new ones or re-open this.
