### ISSUE TITLE
maintainer check: use devel project setting

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#835]
when checking for maintainer the bot currently only looks at Factory resp the Factory devel project. Sometimes, e.g in case of kernel-source in Leap the package intentionally has  a different maintainer than in Factory. So the bot needs to check if the target package has a devel project set and use that maintainer instead.

**Comment by jberry-suse** [comment]
[`add_devel_project_review()`](https://github.com/openSUSE/osc-plugin-factory/blob/7431af4a72ae65d5464a91161345b66f31147e97/check_maintenance_incidents.py#L66) in `MaintenanceChecker` uses `/search/owner` and not a devel check. Is this to what you are referring?

If so then rewrite as explicit devel lookup for target_project/target_package and if no devel then fallback to `openSUSE:Factory`? Using the devel project/package to find maintainers?

Kinda like:

- https://github.com/openSUSE/osc-plugin-factory/blob/3d503c1f2cbcc4dddee904638ad2f5a1b5f0cecf/osclib/request_splitter.py#L139
- https://github.com/openSUSE/osc-plugin-factory/blob/a3d840a6530611644c52840c4bf0476b2f916218/devel-project.py#L156

**Comment by jberry-suse** [comment]
Worked on https://build.opensuse.org/request/show/492800 as it does not require a maintainer review.
