### ISSUE TITLE
repochecker: refactor to support Leap and SLE

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#837]
Per email request. This issue will track the discussion and subissues related to this task.

First up is #764 to not hardcode architectures.

Part of the work will be understanding what the expected workflow is for Leap and SLE. For instance the first blocker that came up is update requests that have builds disabled are immediately rejected since they are not build against Leap 42.3 (like https://build.opensuse.org/request/show/488094). Does it make sense to add a repo for repochecker in previous Leap version updates repo? Similarly, updates coming from SP3 will have the same problem, but in that case I am not sure if the bridge allows for building without first branching the package (could be done to build entire SP3 against Leap 42.3). Then of course the common Factory submissions which of course also do not build for Leap 42.3. Is the intention to enable such repos? For Factory perhaps the repo checker can look back at the devel project which will likely build against 42.3.

**Comment by jberry-suse** [comment]
Presumably, the intent of 866a28adada9f814383c92937ed5815c9d50af5c
```python
        _is_product = re.match(r'openSUSE:Leap:\d{2}.\d', self.tgt_project)
        if self.src_project == 'openSUSE:Factory' and _is_product:
            self.is_shadow_devel = True
            self.shadow_src_project = '%s:Staging:repochecker' % self.tgt_project
```
would seem to be to build Factory packages against Leap. How are the packages expected to be placed in there and is this the same process to be used for 42.2:Updates and SP3?

**Comment by jberry-suse** [comment]
I changed the code to set the shadow devel project as the devel project if the request is from Factory which works properly so long as the devel project has not been updated further. I have some current requests working with this approach.

**Comment by jberry-suse** [comment]
An extremely rough work in progress https://github.com/openSUSE/osc-plugin-factory/compare/master...jberry-suse:repo_checker.

**Comment by lnussel** [comment]
I guess we'd need a script or repochecker itself to fill the shadow project. Can't remember how this was done before. Maybe @aplanas remembers?

An alternative would be to forget about devel projects and only check staging projects. That would mean that staging projects, including adi's always also need to build the architectures repochecker checks.

**Comment by nilxam** [comment]
> It would be good to have some sort of explanation or point to example of what more_repo_candidates is > trying to support in repositories_to_check() so I can port it properly.

It's intend to check the complicate build repository setup also are a valid repository can be check, IIRC for example, devel:languages:perl

**Comment by jberry-suse** [comment]
But what is the end goal? That the package builds against the target archs of the product in a repo using the product's path? If so seems like that would be more straight foward to check. Many times I see the repo checker noting that a package builds in staging and accepting. If the goal is to see that it builds and check install time requirements it seems like checking in a staging would also be the way to go, but if that is what is done how is that different from the existing staging process which will not accept a package that fails to build? lnussel mentioned that the stagings need to build in all the target archs the repo checker checks, but for Leap and TW that would seem to already be the case since only i586 and x86_64 are the only two it looks at. Is there some historical reason for this seemingly duplicate check?

Seems like what the repo checker should do is check the install time requirements and such that are not done by the staging process and leave the rest to the normal process.

Otherwise, the specifics of what is required in some repo checks needs to be laid out. Seems like something along the following is all that is needed.

```python
# sudo code
target_archs = product_target_archs()
for repo in repos: # filtered to ones including product path
    repo_good = True
    for arch in repo.archs:
        if arch in target_archs and repo.status not in ('succeeded', 'excluded'):
              repo_good = False
```

Otherwise, I am really not sure what the code is trying to accomplish.

**Comment by nilxam** [comment]
1) we don't have i586 build in :DVD and adi, yes, we can enable that, *but* does it worth to spend build service resource? we're talking about ``> 1000`` package in :DVD for each staging project, and 2 products.
2) without i586 builds, repochecker ensure i586 and x86_64 is build successful in the devel project or was excluded in case it's non-intel-arch build specific.
3) your sudo code look valid, https://github.com/openSUSE/osc-plugin-factory/blob/master/osclib/checkrepo.py#L588 was there just because(IIRC) we have been seen complicate build repository layout and the strange result, probably empty binaries there, can't remember, but the sudo code here is valid IMO.

**Comment by jberry-suse** [comment]
Extended conversation summary:

- enable `i586` in adi stagings for Leap and Factory
  - catch additional issues
  - relieve the need to fallback to devel project which will likely not work as well for Leap
- look for relevant archs per sudo code above
  - staging (fallback if not all archs provided [ie SLE])
  - source (Factory devel, SLE home:*/etc, Leap commonly useless)
  - could fall back further, but no need for openSUSE:* if adi build change is made

**Comment by lnussel** [comment]
👍  except that Factory may not got so far to enable i586

**Comment by jberry-suse** [comment]
I generally tried to avoid rewriting things as much as possible. I searched for all references to `Factory`, `i586`, and `x86_64` to replace or ensure they were still applicable.

I replaced the repo logic with the sudo code except that instead of looking for a build in any arch it looks for any repos having all product target archs.

There are some bits specific to `-32bit` cross builds for `x86_64` so I tweaked them to allow for the rest of the code to be applied to any arch.

I do not believe we discussed ring-2 needing `i586` during our call so I left that logic as `x86_64` only and wrapped in condition to check if rings to handle SLE.

The main remaining bit seems to be whether this should be done for all target archs or remain just checking one.

```python
self.repo_dir = '%s/repo-%s-%s-x86_64' % (CACHEDIR, 'openSUSE:{}'.format(opts.project), 'standard')
self._mirror_full(PLUGINDIR, self.repo_dir)
```

I ran a couple Factory and Leap:42.3 requests with some promising results, but need to run some more broad runs and try SLE.

The rough code for review: https://github.com/openSUSE/osc-plugin-factory/compare/master...jberry-suse:repo_checker-take-2.

**Comment by jberry-suse** [comment]
Also not sure if desirable to check all arch in `_check_repo_download()` as it was `x86_64` only before, but the code above includes that bit as well.

**Comment by jberry-suse** [comment]
Come to think of it `_check_repo_download()` will either need to remain single arch or restricted to the archs used in stagings (or at least for that part) since it attempts to download packages from each arch. This logic will obviously work for Factory/Leap for both target archs with the current changes.

**Comment by jberry-suse** [comment]
For confirming that this does not break the existing functionality in Factory I will likely add some analysis bits to summarize accept/decline and run existing and modified code against the same set of open requests to look for changed results.

**Comment by jberry-suse** [comment]
Should the user also be abstracted to allow for something other than `factory-repo-checker`? Probably fine to mirror for leap, but less so for SLE unless no one minds.

**Comment by jberry-suse** [comment]
Last comment for now, but another thing I noticed was that it declined a request whose source project was `blocked` due to Factory update. I've seen repochecker make multiple review updates and perhaps it would in this case, but just recording it in case not.

**Comment by lnussel** [comment]
making the user configurable might make sense but is not mandatory.

**Comment by jberry-suse** [comment]
The question of whether to check to execution plan for all archs or just extend the repo checks. It would seem relevant to do so, but for Leap i586 is enabled and so it will check the execution plan which may not be ideal given the target real target is `x86_64`, but that said likely the plan should still succeed if it builds.

I updated the work in progress branch to check all archs, but would need to modify the resulting review change.

**Comment by jberry-suse** [comment]
The bit that still seems unclear is how repochecker ever marks a staging as a good repo. The only `repositories_to_check()` come from which always uses `last_build_success()` from source project. Is there a separate script? Otherwise, I am missing some magic.

For SLE requests and devel projects without Leap enabled we want to use Stagings per discussion which I thought was already happening based on results I have seen like:

-  [Base:System / procps (revision 167) to package openSUSE:Factory / procps](https://build.opensuse.org/request/show/491252)
- `Builds for repo openSUSE:Factory:Staging:B/standard`

But even if I run the review locally I never get that outcome. The Stagings are never considered except during the execution plan which only occurs after the initial repo check which would never pass if not built for target. Assuming someone points out this bit or I figure it out it should just be a matter of ignoring that source project does not build and waiting for staging. From discussion I do not remember if we agreed to enable `i586` for Leap `:DVD` if not some special exception will need to be added to only check for `x86_64`.

**Comment by jberry-suse** [comment]
Still not sure how it ever marks good repo of a Staging. I can see how to change to look there, but I am guessing there is some special sauce deployed somewhere like the commit loop only on packagelists and not in the code base. I looked around on pacakgelists, but I do not see anything that would have the desired effect.

It seems we should rework some of the behavior to make this `repochecker` a bit more consistent especially for the sake of Leap. One trouble spot for Leap is that many times a submission will not be built for Leap before being staged. For Factory that is likely not the case so declining in that case somewhat makes sense, but considering _magically_ repochecker can approve once built in a staging it seems like it ought to always wait for that case.

For example an SLE request:

```
osc api '/build/SUSE:SLE-12-SP3:GA/_result?lastsuccess&package=yast2-installation&pathproject=openSUSE%3ALeap%3A42.3&srcmd5=c15a9f9381c00dee098f94e6d44bb617'
```

Which `404`s since no builds were ever run. Likely whatever logic that seems to eventually pickup a staging in Factory would never be hit and so I'll have to adjust the `last_build_success()` to look for stagings straight away, but it would be nice to see from where that behavior is coming.

The above will result in a review post in state `new` indicating that missing require archs in repo list. While contrasted with a repo that has builds against target for required archs, but are disabled will be `declined`. Seems inconsistent to me and troublesome for Leap. Is there any reason not to just leave review open to allow for staging build and obviously if it fails there picked up by other process as well. Seems the `repochecker` should rarely outright `decline` and rather just indefinitely wait for a pass case to `accept`.

If no one knows where the staging bit is coming from then I'll just tweak `is_buildsuccess()` to fallback to stagings and wait until there is a result. A concern is that posting such comments may result in a lot of repetitive updates as I have not stumbled across a mechanism to delay or check for repeats. I am guessing Factory stays busy enough it takes repochecker a while to process the same request twice. Not sure if that will suffice for Leap with reduce load unless mixed in with existing Factory service.

The refactoring I have done to use the target archs means that `i586` is checked more thoroughly than before and can cause new, but seemingly legitimate failures as I saw with ffmpeg, but that will effect Factory.

I can just start modifying as I see fit, but would like some input from those more familiar with the expected behavior.

**Comment by jberry-suse** [comment]
I am starting to wonder if the output should be completely reworked. Likely in combination with #482 to work in a manor similar to `leaper` except on the staging project level. Otherwise, the review output is somewhat spamy and does not appear terribly useful since many failures of sorts may be included before a success post staging.

The coincides with the tweaks I have made to take into consideration both architecture reports where both must pass in order for the review to be accepted. This also means that intermediate failures will be doubled.

If some sort of early report is desired could also post the individual, non-successful report after 24 hours of not being staged.
