### ISSUE TITLE
Eliminate repo-checker empty commits

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#860]
Seems to make several an hour, but most of which are empty. This seems wasteful and ends up causing cache clears for dashboard files for no reason.

**Comment by jberry-suse** [comment]
Found the spot making these empty commits.

```bash
for i in Factory; do
        file="check_repo-$i"
        osc check_repo -p "$i" 2>&1 | tee "$file"
        osc -d api -X PUT -f "$file" "/source/openSUSE:$i:Staging/dashboard/check_repo"
done
```

Any reasons we do not add this to the actual code base along with a simple get and compare before save? I imagine the new support package bot has the same sort of submit since I've seen those start to pop up as well.

**Comment by jberry-suse** [comment]
Not to mention the `rm -fr ~/co/downloads` line above the loop would seemingly be handled already.

```python
    try:
        shutil.rmtree(DOWNLOADS)
    except:
        pass
    os.makedirs(DOWNLOADS)
```

**Comment by jberry-suse** [comment]
If no one objects, I will add a condition around the `PUT`.

```bash
current = $(osc api "/source/openSUSE:$i:Staging/dashboard/check_repo")
if [ $(< "$file") != "$current" ] ; then
    osc -d api -X PUT -f "$file" "/source/openSUSE:$i:Staging/dashboard/check_repo"
fi
```

**Comment by DimStar77** [comment]
👍

**Comment by jberry-suse** [comment]
Changed to:
```bash
#!/bin/bash

rm -fr ~/co/downloads
for i in Factory; do
        file="check_repo-$i"
        osc check_repo -p "$i" 2>&1 | tee "$file"
        current="$(osc api "/source/openSUSE:$i:Staging/dashboard/check_repo")"
        if [ "$(< "$file")" != "$current" ] ; then
                osc -d api -X PUT -f "$file" "/source/openSUSE:$i:Staging/dashboard/check_repo"
        fi
done
```

With the other source pending the PR.

**Comment by jberry-suse** [comment]
Seems like it makes sense to make things consistent with other service files by using a template for the repochecker service instead of the loop in the bash file. I will plan on making those changes when repochecker is enabled for Leap.

**Comment by jberry-suse** [comment]
Only one commit by repochecker in last 8 hours and it actually has a diff. Will re-open if still an issue.

**Comment by jberry-suse** [comment]
Hmm, still seeing empty commits, but less often.

https://build.opensuse.org/package/rdiff/openSUSE:Factory:Staging/dashboard?linkrev=base&rev=37621

Presumably there are more services running under repochecker user that will need to be tweaked.

**Comment by jberry-suse** [comment]
I am not sure where `dashboard/installcheck` is being updated, but it is one of the only other changes being made by repochecker user and as such seems like a candidate for the empty commits. `grep`'d code and service files on packagelists to no avail.

**Comment by DimStar77** [comment]
```
cat /usr/local/bin/repo-checker 
#!/bin/bash

rm -fr ~/co/downloads
for i in Factory; do
	file="check_repo-$i"
	osc check_repo -p "$i" 2>&1 | tee "$file"
	current="$(osc api "/source/openSUSE:$i:Staging/dashboard/check_repo")"
	if [ "$(< "$file")" != "$current" ] ; then
		osc -d api -X PUT -f "$file" "/source/openSUSE:$i:Staging/dashboard/check_repo"
	fi
done
```

**Comment by jberry-suse** [comment]
Well that makes four locations generating empty commits. :(((((

**Comment by jberry-suse** [comment]
So far this looks like it was the last one!
