### ISSUE TITLE
factory announcer fails to work

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#875]
May 03 09:23:31 packagelists announcer[11111]: found version 20170430
May 03 09:23:31 packagelists announcer[11111]: Traceback (most recent call last):
May 03 09:23:31 packagelists announcer[11111]: File "/usr/local/bin/announcer", line 113, in <module>
May 03 09:23:31 packagelists announcer[11111]: raise Exception("http fail: %s %s" % (res.status, res.reason))
May 03 09:23:31 packagelists announcer[11111]: Exception: http fail: 404 Not Found

Started from Apr 30.

**Comment by nilxam** [comment]
the Changes file not exists in d.o.o

**Comment by DimStar77** [comment]
IIRC, OBS uses this interface on openQA:

https://openqa.opensuse.org/factory-package-news/

=> the latest generated one there is for 0426

**Comment by DimStar77** [comment]
@lnussel  identified an issue on openqa.opensuse.org where this all runs and corrected it; the next snapshot to be released (presumably 0503) will trigger an update .changes file to be published and thus being sent to the -factory mailing list

**Comment by lnussel** [comment]
should be fixed
