### ISSUE TITLE
latest git checkout no longer works with IBS

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/osc-plugin-factory#877]
when using today's git checkout (c921420a1f5918725d3bbc732f17fd12243a8b08 ), I can't use the plugin to list staging:
iosc staging list -p SUSE:SLE-12-SP3:GA
Server returned an error: HTTP Error 404: Not Found
SUSE:SLE-12-SP3:GA:Staging/dashboard

**Comment by nilxam** [comment]
can you run ``iosc -d staging list -p  SUSE:SLE-12-SP3:GA`` ?

I guessing you're running into a upload data fail, but debug log will be very helpful.

**Comment by fcrozat** [comment]
GET https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/_attribute/SUSE:LockedBy
POST https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/_attribute/SUSE:LockedBy
GET https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/_attribute/SUSE:LockedBy
CACHE_MISS https://api.suse.de/statistics/latest_updated?limit=5000 (expired)
GET https://api.suse.de/statistics/latest_updated?limit=5000
CACHE_PUT https://api.suse.de/statistics/latest_updated?limit=5000 None
CACHE_MISS https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/dashboard/config?expand=1 (does not exist)
GET https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/dashboard/config?expand=1
PUT https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/dashboard/config?comment=scripted+update
GET https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/_attribute/SUSE:LockedBy
POST https://api.suse.de/source/SUSE:SLE-12-SP3:GA:Staging/_attribute/SUSE:LockedBy
Server returned an error: HTTP Error 404: Not Found
Date: Wed, 03 May 2017 14:06:24 GMT
Server: Apache/2.4.23 (Linux/SUSE)
Cache-Control: no-cache
Vary: Accept-Encoding
X-XSS-Protection: 1; mode=block
X-Opensuse-Runtimes: {"view":1.3802703469991684,"db":38.434415,"backend":0,"xml":0}
X-Request-Id: b5606148-d001-4bce-875b-244b9c339f3b
X-Opensuse-APIVersion: 2.8.51.git20170420.09740e14a
X-Runtime: 0.088347
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Opensuse-Errorcode: unknown_package
X-Powered-By: Phusion Passenger 5.0.30
Status: 404 Not Found
Content-Type: application/xml; charset=utf-8
Connection: close
Transfer-Encoding: chunked

<status code="unknown_package">
  <summary>SUSE:SLE-12-SP3:GA:Staging/dashboard</summary>
</status>

SUSE:SLE-12-SP3:GA:Staging/dashboard

**Comment by nilxam** [comment]
right, introduced by https://github.com/openSUSE/osc-plugin-factory/commit/a08c55b6028305f4ff64ff06551480a18670d659

**Comment by jberry-suse** [comment]
Interesting, no dashboard package at all `SUSE:SLE-12-SP3:GA`. Sent PR to skip entirely for `SUSE:` projects.
