### ISSUE TITLE
osc staging command LIST - accept LIST being a comma separated list

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#892]
Background: while reworking the staging groups for the haskell mess, I needed to unselect and move a gazillion of packages - I used the various 'adi dashboards' to give me an overview of packages in a specific group.

Then I copied the list of packages in the group and appended this to the 'osc staging select --move' call.

Sadly, the dashboard shows the list comma separated, osc staging command LIST does not know how to handle the comma (it takes it as part of the package name)

It would be cool if we could just strip those commas away

**Comment by jberry-suse** [comment]
Would this make more sense to provide an option to "move from" one staging to another, or you ended up manually filtering list? I suppose in the same way the select proposals are done one could manually tweak the proposal if one was given for a move.

```
select -i --move adi:123 adi:4 adi:5
```

The current `--from` option is curious to me since the from location is automatically determined and still requires a request list.

**Comment by DimStar77** [comment]
in this very case I 'often' used the entire list from a staging, but not always....

a 'staging merge' might be a different thing to consider for the future though (on workable on adi and letter)

**Comment by lnussel** [comment]
what about fixing the dashboard to not use a coma then? :)

**Comment by jberry-suse** [comment]
I suppose it would depend on how the dashboards are setup and which ones, but would seem like a possibility.

**Comment by DimStar77** [comment]
e.g. https://build.opensuse.org/project/staging_projects/openSUSE:Factory/adi:27

**Comment by jberry-suse** [comment]
That's what I assumed, but is that preferred then?

**Comment by jberry-suse** [comment]
Is there a preference? I would imagine it is more common in general to place comma in list except command line. As such the dashboard behavior does not feel off, but if we are the primary consumer and this is a useful case perhaps it is worth changing there.

**Comment by DimStar77** [comment]
imho, the dashboard should stay consistent with the rest of how OBS presents such lists - which means keeping the comma

```
Status: Build finished

17 packages with a direct dependency to this package.
Packages: bbswitch, crash, dpdk, drbd, hdjmod, installation-images:Kubic, installation-images:openSUSE, kernel-firmware, kernel-obs-build, kernel-obs-qa, kmod-testsuite, pcfclock, sysdig, vhba-kmp, virtualbox, xtables-addons, yast2-sound. [-] 
```

Is from https://build.opensuse.org/package/live_build_log/openSUSE:Factory/kernel-default/standard/x86_64

**Comment by jberry-suse** [comment]
Alright, I'll go ahead and merge the PR then.
