### ISSUE TITLE
MaintenanceChecker: allow for project maintainer to submit

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#895]
I need to double check the logic to be sure of what happened, but it seems since the package has a maintainer it did not include the project maintainers which is who submitted the requests.

Should this behavior be changed or desirable? Figured I'd double check.

https://build.opensuse.org/request/show/493930

**Comment by lnussel** [comment]
we rely on the behavior of osc maintainer ie server side implementation of maintainer definition.  This package for whatever reason has explicit maintainers defined. So it's their primary responsibility. Project maintainers are not meant to simply overrule individual package maintainers. They only act as fallback. So the bot is right in this case.

**Comment by jberry-suse** [comment]
That's what I thought, just wanted to make sure.
