### ISSUE TITLE
staging accept: update the version in all .product files

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#937]
Currently, we have multiple .product files in our _product defintion (at least in TW, but I also think it's true for Leap)

We should ensure that all the .product files get the version updated on checkin; this is especially interesting/important now with Kubic, that also prodces a -release rpm

**Comment by adrianschroeter** [comment]
On Donnerstag, 8. Juni 2017, 16:17:07 CEST wrote Dominique Leuenberger:
> Currently, we have multiple .product files in our _product defintion (at least in TW, but I also think it's true for Leap)
> 
> We should ensure that all the .product files get the version updated on checkin; this is especially interesting/important now with Kubic, that also prodces a -release rpm

Are you sure that this is not the same product just in different flavours?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by DimStar77** [comment]
well, one is called openSUSE Tumbleweed (openSUSE.product) one is openSUSE Kubic (openSUSE-Kubic.product)

and they have their versions set independent...

it might be possible to merge this into a single product file, but that won't make it less confusing to manage

**Comment by DimStar77** [comment]
Fixed by #988
