### ISSUE TITLE
consider posting comment on supersede

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#938]
With the advent of #934 (provide diff comments) it is now somewhat misleading that the next time a request is added or removed the supersede changes made in between are reflected in the comment. Previously my understand was the the comment was not re-posted to avoid noise and likely that one had to squint at the comment to know what changed.

Seems like two courses of action:

- update the `requests_comment` to when supersedes are complete to avoid mentioning in the next comment
- post a comment when a supersede is performed

Thoughts?

**Comment by coolo** [comment]
I see no information that is important for the involved developers if you supersede some requests - so I don't think a comment makes sense. I assume you have other staging managers in mind for this notifcation?

**Comment by DimStar77** [comment]
The idea is to 'better' show the information that is currently in Staging:M - which just looks odd (but is not wrong)

```
Requests: 2 added, 1 removed; using select command

    added request#502560 for package relaxngDatatype submitted by @scarabeus_iv
    added request#502562 for package isorelax submitted by @scarabeus_iv
    removed request#502558 for package relaxngDatatype submitted by @scarabeus_iv
```

**Comment by coolo** [comment]
updating the requests_comment is fine, but I'm arguing that for a pure supersede there is no point in posting a new comment/notification

**Comment by jberry-suse** [comment]
We discussed the usefulness of having an overview of actions taken on a staging (#730) with this issue diff being a possible first step. After seeing it in action I am rather happy with the result and have been considering if the comments could be used for this overview log since they already contain formatting, author, notifications, and since cleaned up with staging only represent the current staging flow. As such it seemed potentially useful to add supersede comments given that right now it is somewhat odd the way it shows up.

For example, Staging A is 84% reviewed and I refresh a few hours later to see it is building and want to know why. If not requests are removed or added there will be no comment. As such I have to dig into the meta history or just assume.

Definitely a balance between noise and useful comments which may be an indication that this sort of event information should be logged somewhere else.

As a third option we could leave it the way it is since supersedes are reflected by the next user, but still seems incorrect.

**Comment by jberry-suse** [comment]
Consensus on skipping over supersedes then?
