### ISSUE TITLE
adi command should try to create sub-package in case multiple-specfile

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#946]
adi command should to create sub-package in case multiple-specfile, otherwise sub-package potentially build failed after merged into Factory as it is never built in adi staging.

**Comment by jberry-suse** [comment]
I would imagine the code at [stagingapi.py @ line 1168](https://github.com/openSUSE/osc-plugin-factory/blob/02ee26b3ed45cd5fcf30067651c83addbab5d783/osclib/stagingapi.py#L1168) is responsible. At first glance it wouild seem to always create subpackages, but given upon further inspection.

```python
if sub_prj == project:  # skip inner-project links
    continue
```

I imagine this logic makes sense to letter stagings where subpackages already exist if desired, but is the cause of the lack of subpackages adi. No comment to that effect, but I would imagine that is the reason.

**Comment by lnussel** [comment]
Is this still open? With SLE using adi we may have more people not aware of such details so a fix would be good.

**Comment by jberry-suse** [comment]
I would agree, and why I get a tad annoyed we introduce code the purposely makes this harder.
