### ISSUE TITLE
repo_checker: provide project only mode and write to dashboard container

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#981]
Currently, only runs as part of repo checker.

**Comment by DimStar77** [comment]
As we block file conflicts from entering, any such dashboard is only for 'finding current issues that need to be fixed' - this has no long-living fate, right?

**Comment by jberry-suse** [comment]
Yeah, sorry last thing I posted and it lacks detail. In Leap we have no had this check running and will need to work through the list. Otherwise we can just run manually and track in this issue.

**Comment by jberry-suse** [comment]
It might make sense to just include this in repo-checker. At the beginning of each set run against target project and upload report to dashboard. Then the random bits in shells scripts can be dropped. If using as a source to compare it makes sense to, although I think my previous comment is the best bet there.

**Comment by jberry-suse** [comment]
Performed a one time full run of both Leap:42.3 and Factory:

- https://build.opensuse.org/package/view_file/openSUSE:Leap:42.3:Staging/dashboard/repo_checker?expand=1
- https://build.opensuse.org/package/view_file/openSUSE:Factory:Staging/dashboard/repo_checker?expand=1

**Comment by jberry-suse** [comment]
I would rather not run the new checker with a bash conditional outside to upload output as the old one does. As such it probably makes sense to clean up my local prototype and proceed to add this as a feature and block deployment since previous file will no longer be updated.

Should also delete old file to keep anyone from being confused by stale output.

**Comment by jberry-suse** [comment]
Could also post the results back as a comment per package by reviewing the entire project and mapping package names back using `/build/openSUSE:Factory/standard/x86_64?view=binaryversions` which would likely be a lot more useful than dumping to a file that few ever see.
