### ISSUE TITLE
factory-auto: add maintainer review for delete requests

### ISSUE THREAD

**Issue by jberry-suse** [openSUSE/osc-plugin-factory#983]
Per #964 the `repo-checker` will no longer require deletes originate from a maintainer, but the maintainer should still sign-off. As such it seems best to have `factory-auto` add a review for the maintainer just like it does for submits.

**Comment by DimStar77** [comment]
With this, repo-checker should not 'block'; on non-maintainer created dr then though

**Comment by jberry-suse** [comment]
The previous behavior of blocking is essentially the same and not helpful in that case. I am open to suggested, but if keeping the behavior it seems the consistent/proper way is to add the review. Still need the ability to override in either case. If staging masters are included on devel projects as discussed accepting the review should not be a problem.

My PR already contains the change to repo-checker 2abb0f117979cdf2aff16e2d3d0ebe188d13113d.

**Comment by jberry-suse** [comment]
So final thought, just drop from repo checker?

**Comment by jberry-suse** [comment]
Perhaps instead of maintainer since that seems dubious perhaps `review_team`? Just like submits.
